### PR TITLE
Enable configurable GPU memory allocation of call_variants

### PR DESCRIPTION
**Pull request by A-Tsai**
To port DeepVariant to Apache Spark, the resource allocation should be configurable, including CPU vCores, main memory and GPU memory. In this pull request, we add two more parameters (enable_configurable_gpu and per_process_gpu_memory_fraction) to let users have more flexibility to allocate the resource of GPU memory. If enable_configurable_gpu is true, each call_variants process will allocate GPU memory by the value of per_process_gpu_memory_fraction. (Default is 100) Please help to check whether the modification is proper or not.

### CODE REVIEW

**Comment by A-Tsai** [comment]
> I signed it!

**Comment by pichuan** [comment]
Hi @A-Tsai ,
I think our setup on GitHub might be a bit confusing right now.
Because the way our repo is set up, the main DeepVariant repo can't directly merge from external pull requests. 

We will need to internally test your pull request, and will have to internally make a code change which will be exported to GitHub later. When we make the code change internally, we will point to your PR in the commit log.
Please let us know if you're ok with that. If so, we'll proceed with that. Thank you.

**Comment by A-Tsai** [comment]
> Hi @A-Tsai ,
> I think our setup on GitHub might be a bit confusing right now.
> Because the way our repo is set up, the main DeepVariant repo can't directly merge from external pull requests.
> 
> We will need to internally test your pull request, and will have to internally make a code change which will be exported to GitHub later. When we make the code change internally, we will point to your PR in the commit log.
> Please let us know if you're ok with that. If so, we'll proceed with that. Thank you.

Yes, I have no problems on it. Please help to verify the PR.

**Comment by gunjanbaid** [comment]
@A-Tsai I want to make sure I understand your use case. You want GPU to be used for the initialization step with the specified fraction of memory. In case the GPU is not available, you want to use CPU, limited to one thread on one core. Is this correct?

**Comment by A-Tsai** [comment]
@gunjanbaid Actually, this pull request will take effect when enable the enable_configurable_gpu flag. I try to minimize the code change as possible as I can, so there is no any change in CPU mode. Since CPU resource allocation of Tensorflow can't be limited to one threat, this pull request doesn't change any configuration in CPU mode. It might introduce a little bit overhead due to context switch when running on Spark, but it won't have any impact on turnaround time from my experiments.

**Comment by gunjanbaid** [comment]
@A-Tsai In the next release, we plan to add a flag to `call_variants` that will allow users to pass in any desired configuration options for the TensorFlow session config. We won't hard code any options, but you will be able to pass in all of the options included in this pull request. The code will be slightly different from what you have specified as the session configuration will be passed to [the estimator](https://github.com/google/deepvariant/blob/5e6fe205b984c6be116dcacafdfd83ce1df4d2e9/deepvariant/call_variants.py#L344), rather than [this code block](https://github.com/google/deepvariant/blob/5e6fe205b984c6be116dcacafdfd83ce1df4d2e9/deepvariant/call_variants.py#L330). Thanks for the suggested changes!

**Comment by A-Tsai** [comment]
@gunjanbaid Even better. Looking forward to the next release.

**Comment by pichuan** [comment]
This is included in our latest release:
https://github.com/google/deepvariant/releases/tag/v0.8.0

Thank you for your contribution to DeepVariant!

**Pull request closed without merging**
