### PR TITLE
Update deepvariant-pacbio-model-case-study.md

### PR DESCRIPTION
**Pull request by pichuan**
We are not taking pull requests at this time.

The text is from @williamrowell .
This change is done by a team member directly on the r1.1 branch, and will be added internally for future relevant versions too.

### CODE REVIEW

**Comment by pichuan** [comment]
@MariaNattestad I'm waiting for @williamrowell to confirm that this looks good. Once he confirms, I'll ask you to take a look and merge. Thanks!

**Comment by williamrowell** [comment]
Looks good to me.  Will the flags will stay the same in the next release?

**Comment by pichuan** [comment]
@williamrowell yes, the flags will stay the same in the next release for DeepVariant, and we're adding this to DeepTrio too.

**Review by MariaNattestad — APPROVED** [review]
LGTM

**Pull request merged**
