### PR TITLE
Use OpenVINO from pip

### PR DESCRIPTION
**Pull request by dkurt**
* Install OpenVINO by pip
* Update OpenVINO to latest 2021.3 version
* Use `enum34==1.1.8` to fix "AttributeError: module 'enum' has no attribute 'IntFlag'" (https://github.com/python-poetry/poetry/issues/1122#issuecomment-628037127)

test run: https://github.com/dkurt/deepvariant/actions/runs/755874669

### CODE REVIEW

**Comment by pichuan** [comment]
Thanks @dkurt ! 
I'll take a look next week and make sure I can incorporate the changes internally.
Can you confirm again that you're ok with us doing that? (I'll add a pointer to this PR when I make the internal change, so that the commit log will have the information.

Thanks.

**Comment by dkurt** [comment]
@pichuan, Sure, I don't mind if you just copy the changes. Yes, this way is valid because OpenVINO from pip uses manylinux toolchain so it's compatoble with Ubuntu 16.04 and allows to upgrade to newer versions.

**Comment by pichuan** [comment]
@dkurt FYI: This is now the merged internally and will come out in the next release.
Thanks!

**Comment by pichuan** [comment]
@dkurt Question for you: I'm working an updates to update to Ubuntu20.04, TF2.5, etc.
Want to check in with you on whether we need to update any OpenVINO version before the next release.
Let me know! If it's easier through email, please email me at pichuan@google.com. Thanks!

**Comment by dkurt** [comment]
Hi, @pichuan! OpenVINO 2021.3 is the latest version. 2021.4 will be released only at least in next month so it's OK to use 2021.3. Thanks!

**Comment by pichuan** [comment]
Thanks @dkurt ! 2021.3 sounds good. I won't make any changes now.

**Comment by pichuan** [comment]
@dkurt One more question - I'm comparing runtime on TF 2.5 and I have another question for you. Can you send me an email at at pichuan@google.com and we can discuss in more details? (I don't have your email address :))

**Pull request closed without merging**
