### PR TITLE
improve call_variants performance

### PR DESCRIPTION
**Pull request by fo40225**
improve call_variants performance

### CODE REVIEW

**Comment by gunjanbaid** [comment]
Hi @fo40225, thank you so much for this pull request. At the moment we cannot accept external contributions (see https://github.com/google/deepvariant/blob/master/CONTRIBUTING.md) as we don't yet have a mechanism setup to resync changes from GitHub back into our codebase within Google. We will look into these changes and are happy to submit a patch after internal testing and benchmarking. Are you ok with that?

**Comment by pgrosu** [comment]
@fo40225 Try as you might, Google will not be accepting your changes for this project - though this could become entertaining so I'm breaking out the popcorn :)

**Comment by fo40225** [comment]
I am fine with you making this change internally and releasing in the next release.

**Comment by pichuan** [comment]
@fo40225 Thank you so much! @gunjanbaid will update internally. It will show up in our next release (hopefully soon! We're working on it). We will recognize your contribution in the release notes.

@pgrosu We strongly appreciate the contributions of yourself and others to the improvement of DeepVariant. We are happy to incorporate pull requests such as this, but right now have to do so indirectly due to technical configuration. Most internal Google projects use a slightly different tool chain from Github, which is a bit faster for us to develop with, so we keep our source of truth internally and use copybara to export to GitHub. :) Among Google open source repos, some are configured differently (for example, our sibling repo Nucleus can take external PRs). When we do incorporate information from a PR such as this, we will recognize the contribution and author in the release notes.

**Comment by pichuan** [comment]
Thanks for the updates @fo40225 .

We've also been communicating through emails. To give a quick update here: after a few internal testing, it seems like the current implementation of the async writer is missing records. We're still looking through this with @fo40225 . Hopefully it'll get resolved eventually. When we can confirm the results are consistent as before, we will be able to add this to our codebase.
Thank you!

**Comment by pichuan** [comment]
Part of this PR is included in the latest release: https://github.com/google/deepvariant/releases/tag/v0.8.0
Thank you for your contribution!

@fo40225 I'll try to schedule a separate discussion about the async writer with you.

**Comment by pichuan** [comment]
Hi all,
I'm posting an update to this PR after talking to @fo40225: 
Our team has done changes similar to the latest code in this PR (using Close() on writer). Our current findings are:
1. With async writer, if `call_variants` doesn't write to a .gz file, the run finishes fine and results now seem complete (meaning, the VCF and GVCF after `postprocess_variants` are the same as the results when async writer is turned off)
1. However, when outputting as a .tfrecord.gz file, currently async writer in `call_variants` here will output a .gz file that will cause an issue in the following `postprocess_variants` step. This issue is currently blocking us adding in the suggested change in this PR.

The current plan is our team will try to fix the issue in the second item. We want to confirm that the outputs from the async writer proposed in this PR are completely correct before we proceed.

Thanks.

**Pull request closed without merging**
